# Generated by Django 3.2 on 2021-04-16 04:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manner', models.IntegerField(auto_created=True, default=50)),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='이메일 주소')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField()),
                ('title', models.CharField(max_length=30)),
                ('category', models.CharField(blank=True, choices=[('남성패션/잡화', '남성패션/잡화'), ('여성의류', '여성의류'), ('뷰티/미용', '뷰티/미용'), ('기타 중고물품', '기타 중고물품'), ('가구/인테리어', '가구/인테리어'), ('식물', '식물'), ('스포츠/레저', '스포츠/레저'), ('여성잡화', '여성잡화'), ('유아동/유아도서', '유아동/유아도서'), ('게임/취미', '게임/취미'), ('도서/티켓/음반', '도서/티켓/음반'), ('반려동물용품', '반려동물용품'), ('디지털/가전', '디지털/가전'), ('생활/가공식품', '생활/가공식품'), ('삽니다', '삽니다')], max_length=10)),
                ('price', models.IntegerField()),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='daangns.post')),
            ],
            options={
                'ordering': ('-created_date',),
            },
        ),
    ]
